DROP TABLE Uzytkownik CASCADE;
DROP TABLE Seria CASCADE;
DROP TABLE Konkurs CASCADE;
DROP TABLE Uczestnik CASCADE;
DROP TABLE Reprezentacja CASCADE;
DROP TABLE Zgloszenie CASCADE;
DROP TABLE Skok CASCADE;